name: Deploy Lambda

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::365502632637:role/github-actions-deploy-lambda
          aws-region: sa-east-1

      - name: Empacotar código em zip
        run: zip function.zip lambda_function.py

      - name: Atualizar código da Lambda
        run: |
          aws lambda update-function-code \
            --function-name minha-primeira-lambda \
            --zip-file fileb://function.zip